#%RAML 1.0 Example
title: Example-API
/blogs:
  description: Collection of available blog in Knoldus site
  get:
    description: Get a list of blog based on the blog title.
    queryParameters:
      blogTitle:
        description: "The title of the blog to search"
        required: true
        minLength: 5
        type: string
        example: "Intro"
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "blogs": [
                  {
                    "blogId": "440e4450-y45n-e432-889900660111",
                    "blogTitle": "marklogic vs mongodb"
                  },
                  {
                    "blogId": "220e8933-n08m-82r4-a987-99774400110333",
                    "blogTitle": "Introduction to DBMS"
                  },
                  {
                    "blogId": "560f9904-n45e-90w1-i908-113300330222",
                    "blogTitle": "Introduction to Postman"
                  }
                ]
              }
